id: IE3ACE254
initial_creation_type: ebook
source_metadata:
  id: IBA-GR-13
  title: ༄༅། །ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་མན་ངག་གི་བསྟན་བཅོས་མངོན་པར་རྟོགས་པའི་རྒྱན་འགྲེལ་པ་དང་བཅས་པའི་དཀའ་བའི་གནས་རྣམ་པར་བཤད་པ་ཡུམ་དོན་རབ་གསལ་ཞེས་བྱ་བ་བཞུགས་སོ།།
  author: མཛད་པ་པོ། གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
  authors: &id001
  - མཛད་པ་པོ། གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
  sku: IBA-GR-13
  cover: IBA-GR-13.jpg
  volume: {}
ebook_metadata:
  title: ༄༅། །ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་མན་ངག་གི་བསྟན་བཅོས་མངོན་པར་རྟོགས་པའི་རྒྱན་འགྲེལ་པ་དང་བཅས་པའི་དཀའ་བའི་གནས་རྣམ་པར་བཤད་པ་ཡུམ་དོན་རབ་གསལ་ཞེས་བྱ་བ་བཞུགས་སོ།།
  authors: *id001
  sku: IBA-GR-13
  cover: IBA-GR-13.jpg
layers:
- Author
- BookTitle
- Chapter
- Citation
- Commentary
